### ISSUE TITLE
Display languages in an order that makes sense

### ISSUE THREAD

**Issue by Vesihiisi** [Vesihiisi/Wikidata-Senses#4]
Display the languages on the front page in an order that makes sense, i.e. either alphabetically or by number of entries.

The [query](https://github.com/Vesihiisi/Wikidata-Senses/blob/master/app.py#L114) is supposed to order by number of entries, and works as expected locally, but mixes it up on toolforge.

**Comment by lucaswerkmeister** [comment]
> works as expected locally, but mixes it up on toolforge

Idea: you’re probably using a more recent Python version locally than on Toolforge. Dictionaries preserve order since Python 3.6 (and this was changed from an implementation detail to part of the specification in 3.7), but Toolforge is, if I recall correctly, on Python 3.4. See also [this lexeme-forms commit](https://phabricator.wikimedia.org/R2362:4f0d8cc6cbb425fe85a90bb6589bfc37d267e6f5).
